# kubernetes/training-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-service
  template:
    metadata:
      labels:
        app: training-service
    spec:
      containers:
      - name: training-service
        image: ${REGISTRY}/training-service:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: dqn-config
        volumeMounts:
        - name: shared-volume
          mountPath: /app/models
        - name: shared-volume
          mountPath: /app/logs
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-volume-claim
      initContainers:
      - name: wait-for-monitoring
        image: busybox
        command: ['sh', '-c', 'until wget -qO- http://monitoring-service:5001/health; do echo waiting for monitoring-service; sleep 2; done']
---

